### ISSUE TITLE
Safe mode crash

### ISSUE THREAD

**Issue by ghost** [douglas-srs/Safe-Alarm-3-iOS-10#6] opened 2017-03-03 06:41 UTC
When using the arithmetic feature on alarms when you press the lock button it then makes the alarm equation regenerate and over lap so you can't actually see it also after a few times it throws you into safe mode

**Comment by douglas-srs** [comment] 2017-03-03 11:23
Thanks for reporting, I will investigate.

**Comment by douglas-srs** [comment] 2017-03-03 11:31
I couldn't reproduce the issue, how did you configure the Lock Button Action in settings? Are you on Lockscreen or Homescreen? Please give me the exact steps to reproduce this and if possible install Crash Reporter so when it crashes you can send me the Crash Logs.

**Comment by ghost** [comment] 2017-03-03 14:59
Okay so I fixed the overlap issue by changing the lock button to no action however the entering of the answer of the equation is extremely laggy and barely works

**Comment by douglas-srs** [comment] 2017-03-03 15:01
what action was it before and were you on Lockscreen or Homescreen? I can't fix it if I can't reproduce the bug.

**Comment by ghost** [comment] 2017-03-03 15:02
Sorry it was on snooze alarm before and on the lock screen

**Comment by douglas-srs** [comment] 2017-03-03 15:03
I will make some tests, thank you!

**Comment by ghost** [comment] 2017-03-03 15:12
Don't know if it's helpful but something I noticed 

When the alarm goes off and asks for your answer the screen flashes red even though it's disabled and if you press lets say 1 it won't respond until the red screen has flashed then one will act pressed and this carries on

**Comment by douglas-srs** [comment] 2017-03-03 22:28
I tested every situation and still wasn't able to reproduce the issue, what version are you using? 3.0.4b?

**Comment by ghost** [comment] 2017-03-03 22:35
No 3.0.5b-1+debug

Must be a conflicting tweak I'll check my other tweaks and let you know

**Comment by ghost** [comment] 2017-03-03 22:41
It managed to crash again when trying to enter the answer 
http://pastebin.com/p9SXXA8b
That's the crash log

**Comment by douglas-srs** [comment] 2017-03-03 22:43
Alright, please send me this file: /var/mobile/Library/Preferences/net.douglassoares.SafeAlarm3.plist or just go through Safe Alarm Settings > About and Email Support and it will send the file to me.

**Comment by ghost** [comment] 2017-03-03 22:54
I've sent it to this email admin@douglassoares.net

And I tried it on my iPad Air 2 iOS 10.2 and same issue both devices are 10.2 the entering of answer is laggy and the flash screen happens

**Comment by ghost** [comment] 2017-03-03 22:56
Oh and iPad has no other tweaks on

**Comment by ghost** [comment] 2017-03-04 22:05
It's only on the lock screen the flash and lag happens

**Comment by douglas-srs** [comment] 2017-03-07 11:18
I changed the way the flash view appears, I will release a beta in the next few hours, please test again after that, thank you :)

**Comment by douglas-srs** [comment] 2017-03-07 13:41
Just released a new beta, try it please.

**Comment by ghost** [comment] 2017-03-07 17:12
Exact same red flash screen aswell on both devices

**Comment by douglas-srs** [comment] 2017-03-07 18:47
I will make some more tests. Did it stop crashing at least?

**Comment by ghost** [comment] 2017-03-07 18:48
Yes it did

**Comment by douglas-srs** [comment] 2017-03-07 18:53
Do you mind making a video? You can find some screen recorder tweaks on cydia. That would be super helpful!

**Comment by ghost** [comment] 2017-03-07 18:54
No problem I'll do it later on tonight or tomorrow at the latest

**Comment by douglas-srs** [comment] 2017-03-07 18:54
Thanks!

**Comment by ghost** [comment] 2017-03-07 19:07
http://www5.zippyshare.com/v/80NtJNZv/file.html

There's a download link for the video

**Comment by douglas-srs** [comment] 2017-03-07 23:10
One last thing, please go to Flash Settings and send me a screenshot.

**Comment by ghost** [comment] 2017-03-07 23:12
http://www31.zippyshare.com/v/pMNTaCEi/file.html
Sorry about the download links doing it all from device

**Comment by douglas-srs** [comment] 2017-03-09 13:02
Uow, so it's Flashing even with Flash turned off... I will release a new beta as soon I finish a new feature and then you tell me if it fixed it. thank you for your patience.

**Comment by douglas-srs** [comment] 2017-03-10 21:15
Hey, I will release the tweak soon, tell me if the issue continues after installing it.

**Comment by ghost** [comment] 2017-03-10 21:23
Shall I try the latest debug version on your repo or haven't you changed anything for it on that update?

**Comment by douglas-srs** [comment] 2017-03-10 21:24
I didn't change anything related to that problem but you can try the new Playlist Feature :)

**Comment by douglas-srs** [comment] 2017-03-13 13:11
Hey, I changed a few things now and will release a beta in a few hours, please try! thank you!

**Comment by ghost** [comment] 2017-03-13 19:24
Perfect it works great now only other thing is that the backspace button on arithmetic isn't visible

**Comment by douglas-srs** [comment] 2017-03-13 19:30
uow, how did I miss that? 😲
I will fix it now and close this issue, thank you for your time :)


----------------------------

Att,
*Douglas Soares*

**Closed as completed** 2017-03-13 19:30 UTC
